# This file is machine-generated - editing it directly is not advised

julia_version = "1.10.0-rc3"
manifest_format = "2.0"
project_hash = "3ec3cda12b6de964321693f8135f0ce728085bf1"

[[deps.Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[deps.Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"
